//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStoryApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Franchise
    {
        public int Id { get; set; }
        public string Logo { get; set; }
        public string Name { get; set; }
        public string Origin { get; set; }
        public string Type { get; set; }
        public int FirstAppearance { get; set; }
        public string CreatedBy { get; set; }
        public int Count { get; set; }
        public string VideoLink { get; set; }
    }
}
